[build]
command = "hugo --minify --baseURL $URL"
publish = "public"

[build.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --minify --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --minify --baseURL $DEPLOY_PRIME_URL"
